### ISSUE TITLE
<http://dev.marineinfo.org/id/publication/246614> exceeds single line max_batch_size

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/py-RDF-store#12]
logs:

lwua_graphdb   | [INFO ] 2024-02-21 09:49:12,215 [repositories/kgap | c.o.g.s.h.GraphDBQueryResultHandler] POST query -1410643714
lwua_graphdb   | [INFO ] 2024-02-21 09:49:12,216 [repositories/kgap | c.o.g.s.TupleQueryResultView] Request for query -1410643714 is finished
dereferencer   | 2024-02-21 09:49:12 @WebAccess.py             [INFO  ] content of http://dev.marineinfo.org/id/publication/246614 added to the triplestore
dereferencer   | 2024-02-21 09:49:12 @pytravharv.py            [ERROR ] single line exceeds max_batch_size
dereferencer   | 2024-02-21 09:49:12 @pytravharv.py            [ERROR ] Error running dereference tasks
dereferencer   | 2024-02-21 09:49:12 @__main__.py              [INFO  ] teardown

Exspected behaviour:

Log this to the user but don't assert and fail on the spot :)

**Comment by marc-portier** [comment]
fixed in dev branch - but not closed until merged with `main`
