### ISSUE TITLE
provide test for __main__ method

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/py-RDF-store#2]
because it is best to test that too of course

but also because I doubt the current implementation works as it is not satisfying the contract of the `ingest(graph: Graph)` method

this part seems wrong:
```python
    if args.input:
        with open(args.input, "r") as f:
            data = f.read()
            target_store.insert(data)
```
this is not passing in a graph, but a string?

**Comment by cedricdcc** [comment]
Deleted __main__.py for now since it has no real direct use.
