### ISSUE TITLE
test if skolemize behaves as required

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/py-RDF-store#32]
We are encountering an issue with the rdflib library's skolemize function when working with GraphDB. Specifically, the function is generating more triples in a single blank node than expected. 

### Expected Behavior

The skolemize function should correctly transform blank nodes into skolemized URIs, ensuring that each blank node is represented by a single URI in the output.
### Actual Behavior

Instead, multiple triples are being grouped into a single blank node, leading to an incorrect representation of the graph.

### Proposed Solution

We propose writing comprehensive tests for the skolemize function to identify the root cause of this issue. These tests should cover various scenarios, including different graph structures and configurations, to ensure that the function behaves correctly in all cases.

**Comment by marc-portier** [comment]
it seems like it does work as should
tests added in #34 - together with identified sub-problem of #29
