### ISSUE TITLE
roll out 0.0.1

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/py-RDF-store#35]
already passed due date
but now also includes fixes for the nasty #29 and #32

depends on PR #34 to be merged first -- which can happen after review

**Comment by cedricdcc** [comment]
All mentioned pull requests merged. PyPi was not mentioned in this milestone so it will be skipped for the next one

**Comment by marc-portier** [comment]
hm, PyPi was what I implied with "roll out" 

did we at least put a github release tag?

**Comment by cedricdcc** [comment]
The milestone is not closed yet so a tag can be added retroactively

**Comment by cedricdcc** [comment]
tag was created https://github.com/vliz-be-opsci/py-RDF-store/releases/tag/0.0.1 for https://github.com/vliz-be-opsci/py-RDF-store/commit/a30c39016ef5e3e0027a38881cb94b07d7d61bbe
